
# op cache production mode
opcache.enable=1
opcache.enable_cli=0
opcache.memory_consumption=256
opcache.max_accelerated_files=20000
opcache.validate_timestamps=0
opcache.save_comments=1

# op cache dev mode
opcache.validate_timestamps=1
opcache.revalidate_freq=1

# Enable APCu for PHP-FPM (you must install APCu)
apc.enable=1
apc.shm_size=64M